import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import React from 'react'

import Link from 'next/link';
import jfile from '../data/home/file.json';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  // console.log(jfile.grid);
  const [ chatInput, setInput ] = React.useState('');
  const [ chatResp, setResponse] = React.useState();

  async function onSubmit(event) {
    event.preventDefault();

    if(!chatInput){
      alert("Please enter a valid text")
      return;
    }

    try {
      const response = await fetch("/api/chatgpt", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ input: chatInput }),
      });

      const data = await response.json();
      if (response.status !== 200) {
        throw data.error || new Error(`Request failed with status ${response.status}`);
      }

      setResponse(data.result);
      setInput("");
    } catch(error) {
      // Consider implementing your own error handling logic here
      console.error(error);
      alert(error.message);
    }
  }

  // console.log(chatResp);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
            {/* <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a> */}
          </div>
        </div>
        <div className={styles.center}>
          <form className={styles.form} onSubmit={onSubmit}>
            <input
              type="text"
              name="text"
              placeholder="Create a copywrite text about/for..."
              value={chatInput}
              onChange={(e) => setInput(e.target.value)}
            />
            <button type="submit"> Go! </button>
          </form>
          {/* <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          /> */}
          {/* <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div> */}

          {
            chatResp && 
            <div className={styles.textContainer} >
              <p className={inter.className} >
                {chatResp}
              </p>
            </div>
          }
        </div>
        <div className={styles.grid}>


          {jfile.grid.map(item => {
            return <Link href={item.link} className={styles.card} >
                <h2 className={inter.className}>
                  {item.title} <span>-&gt;</span>
                </h2>
                <p className={inter.className} >
                  {item.description}
                </p>
              </Link>
          })}


        </div>
      </main>
    </>
  )
}
